# Generated by Django 2.0.3 on 2019-04-13 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Productlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ManyToManyField(blank=True, related_name='toppings', to='orders.Productlines')),
            ],
        ),
        migrations.AddField(
            model_name='productlines',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='orders.Products'),
        ),
        migrations.AddField(
            model_name='prices',
            name='productlines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lines', to='orders.Productlines'),
        ),
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='orders.Prices'),
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='orders.Products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='productlines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product_lines', to='orders.Productlines'),
        ),
        migrations.AddField(
            model_name='orders',
            name='toppings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_toppings', to='orders.Toppings'),
        ),
    ]
