# Generated by Django 2.0.3 on 2019-04-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Toppings',
            new_name='Topping',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='productlines',
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='orders.Price'),
        ),
        migrations.RenameModel(
            old_name='Productlines',
            new_name='Productline',
        ),
        migrations.DeleteModel(
            name='Prices',
        ),
        migrations.AddField(
            model_name='price',
            name='productlines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_line', to='orders.Productline'),
        ),
    ]
