# Generated by Django 2.0.3 on 2019-04-13 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190413_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('TotalPrice', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='orders.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='productlines',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='productline',
            name='size',
        ),
        migrations.AlterField(
            model_name='price',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='orders.Size'),
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.AddField(
            model_name='order',
            name='productlines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product_lines', to='orders.Productline'),
        ),
        migrations.AddField(
            model_name='order',
            name='toppings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_toppings', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='order',
            name='unitprice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='orders.Price'),
        ),
    ]
