# Generated by Django 2.0.3 on 2019-04-14 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_price_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='product',
        ),
    ]
