# Generated by Django 2.0.3 on 2019-04-14 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_price_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='priced_product', to='orders.Product'),
            preserve_default=False,
        ),
    ]
