# Generated by Django 2.0.3 on 2019-04-14 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190414_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_sizes', to='orders.Size')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('TotalPrice', models.FloatField()),
                ('AddOn', models.ManyToManyField(blank=True, null=True, related_name='addOn', to='orders.AddOn')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='orders.Product')),
                ('productlines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product_lines', to='orders.Productline')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='productlines',
        ),
        migrations.RemoveField(
            model_name='order',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='order',
            name='unitprice',
        ),
        migrations.AlterField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priced_product', to='orders.Product'),
        ),
        migrations.RemoveField(
            model_name='topping',
            name='name',
        ),
        migrations.AddField(
            model_name='topping',
            name='name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='purchase',
            name='toppings',
            field=models.ManyToManyField(blank=True, null=True, related_name='toppings', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='unitprice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='orders.Price'),
        ),
    ]
