# Generated by Django 2.0.3 on 2019-04-14 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190414_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='size',
        ),
    ]
