# Generated by Django 2.0.3 on 2019-04-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_addon_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='AddOn',
            field=models.ManyToManyField(blank=True, related_name='addOn', to='orders.AddOn'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='orders.Topping'),
        ),
    ]
