# Generated by Django 2.0.3 on 2019-04-14 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190414_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='Dependent_Productline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_product_line', to='orders.Productline'),
        ),
    ]
