# Generated by Django 2.0.3 on 2019-04-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_addon_dependent_productline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='Dependent_Productline',
        ),
        migrations.AddField(
            model_name='addon',
            name='Dependent_Productlines',
            field=models.ManyToManyField(blank=True, null=True, related_name='dependent_product_line', to='orders.Productline'),
        ),
    ]
