# Generated by Django 2.0.3 on 2019-04-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20190414_0355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addon',
            old_name='Dependent_Productlines',
            new_name='dependent_Productline',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='AddOn',
            new_name='addOns',
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
