# Generated by Django 2.0.3 on 2019-04-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20190414_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addon',
            old_name='dependent_Productline',
            new_name='Productlines',
        ),
        migrations.AddField(
            model_name='topping',
            name='Productlines',
            field=models.ManyToManyField(blank=True, related_name='topping_product_line', to='orders.Productline'),
        ),
    ]
