# Generated by Django 2.0.3 on 2019-04-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20190414_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='Productlines',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='Productlines',
        ),
        migrations.AddField(
            model_name='productline',
            name='addOns',
            field=models.ManyToManyField(blank=True, related_name='subs_addOn', to='orders.AddOn'),
        ),
        migrations.AddField(
            model_name='productline',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='pizza_toppings', to='orders.Topping'),
        ),
    ]
