# Generated by Django 2.0.3 on 2019-04-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20190414_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='productlines',
        ),
        migrations.AddField(
            model_name='productline',
            name='require_toppings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productline',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='pizza_toppings', to='orders.Topping'),
        ),
    ]
