# Generated by Django 2.0.3 on 2019-04-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20190415_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='productlines',
        ),
        migrations.AddField(
            model_name='productline',
            name='addOns',
            field=models.ManyToManyField(blank=True, related_name='subs_addOn', to='orders.AddOn'),
        ),
    ]
