# Generated by Django 2.0.3 on 2019-04-15 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_purchase_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='size',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.Size'),
            preserve_default=False,
        ),
    ]
