# Generated by Django 2.0.3 on 2019-04-15 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_purchase_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
    ]
